# Generated by Django 4.2.7 on 2025-07-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_cti_indexes'),
        ('tickets', '0002_add_service_description'),
    ]

    operations = [
    ]
