# Generated by Django 4.2.7 on 2025-07-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_merge_20250727_0138"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctirecord",
            name="bu_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ctirecord",
            name="resolver_group_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="ctirecord",
            index=models.Index(
                fields=["category", "type"], name="tickets_cti_categor_62a61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ctirecord",
            index=models.Index(
                fields=["resolver_group"], name="tickets_cti_resolve_f376e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "assigned_to"], name="tickets_tic_status_542056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_at", "status"], name="tickets_tic_created_df8aa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["predicted_cti", "corrected_cti"],
                name="tickets_tic_predict_5f408a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["prediction_confidence"], name="tickets_tic_predict_72c321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="tickets_tic_assigne_e36302_idx"
            ),
        ),
    ]
