# Generated by Django 4.2.7 on 2025-07-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_merge_20250727_0957'),
        ('tickets', '0004_ctirecord_bu_description_and_more'),
    ]

    operations = [
    ]
