# Generated by Django 4.2.7 on 2025-07-27 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ctirecord_bu_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctirecord",
            name="example_based_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ctirecord",
            name="example_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ctirecord",
            name="last_example_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FewShotExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_content", models.TextField()),
                ("original_summary", models.CharField(max_length=200)),
                ("original_description", models.TextField()),
                (
                    "classification_source",
                    models.CharField(
                        choices=[
                            ("ai", "AI Classified"),
                            ("confirmed", "Agent Confirmed"),
                            ("corrected", "Agent Corrected"),
                        ],
                        default="ai",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=1.0)),
                ("user_department", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("embedding_diversity_score", models.FloatField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cti_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="few_shot_examples",
                        to="tickets.ctirecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cti_record", "classification_source"],
                        name="tickets_few_cti_rec_4587d5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="tickets_few_created_5356fa_idx"
                    ),
                    models.Index(
                        fields=["confidence_score"],
                        name="tickets_few_confide_e534d1_idx",
                    ),
                ],
            },
        ),
    ]
