# Generated by Django 4.2.7 on 2025-07-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_few_shot_examples'),
        ('tickets', '0005_merge_20250727_1219'),
    ]

    operations = [
    ]
