# Generated by Django 4.2.19 on 2025-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('end_user', 'End User'), ('support_engineer', 'Support Engineer'), ('admin', 'Administrator')], default='end_user', max_length=20),
        ),
    ]
