# Generated by Django 4.2.19 on 2025-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_similar_cti_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='similar_cti_records',
            field=models.JSONField(default=list, help_text='Top 5 similar CTI records in JSON format'),
        ),
    ]
