# Generated by Django 4.2.19 on 2025-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_similar_cti_records'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ctirecord',
            unique_together={('bu_number', 'category', 'type', 'item', 'resolver_group', 'request_type', 'sla', 'service_description', 'bu_description', 'resolver_group_description')},
        ),
        migrations.AddIndex(
            model_name='ctirecord',
            index=models.Index(fields=['request_type'], name='tickets_cti_request_b62501_idx'),
        ),
    ]
