# Generated by Django 4.2.19 on 2025-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ctirecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.TextField(),
        ),
    ]
